version: '3'

services:
  webserver:
    image: nginx:latest
    networks:
      - foundry-network
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  foundry:
      image: felddy/foundryvtt:release
      hostname: a-real-domain-name.com
      container_name: foundry-server
      networks:
        - foundry-network
      init: true
      restart: "unless-stopped"
      volumes:
        - type: bind
          source: ./foundry-user-data/ 
          target: /data
      environment:
        - FOUNDRY_PASSWORD=xxx
        - FOUNDRY_USERNAME=xxx
        - FOUNDRY_ADMIN_KEY=xxx
      ports:
        - target: 30000
          published: 30000
          protocol: tcp

networks:
  foundry-network:
    external:
      name: foundry-network